### ISSUE TITLE
Slideshow images way too small, appears to be using square

### ISSUE THREAD

**Issue by snydman** [projectblacklight/spotlight#1158]
see https://exhibits.stanford.edu/maps-of-africa/default-exhibit/feature/cape-of-good-hope#slideshow

![image](https://cloud.githubusercontent.com/assets/3279382/8239634/0060e880-15b2-11e5-87b2-02813a3ee6c5.png)

**Comment by cbeer** [comment]
We should index a field with an appropriately-sized IIIF image, say:

https://stacks.stanford.edu/image/iiif/bj356mh7176%2Fbj356mh7176_00_0001/full/!800,600/0/default.jpg

and define:

```ruby
config.view.slideshow.thumbnail_field = :whatever_field_we_create
```

**Comment by cbeer** [comment]
This ticket is actually more difficult than that, because the slideshow view consists of two different parts -- the gallery layout that triggers the slideshow, and the slideshow itself. We don't (yet) have a way to render different sized images for these. It seems like we'll need a different `render_thumbnail_tag`-like method to handle the full slideshow.
