### ISSUE TITLE
Thumbnail selection options are limited & need scrolling through available options

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1603]
See screenshot. This is an exhibit with hundreds of photos. When entering a keyword to select a thumbnail to display for a feature or browse page, the first ~5 thumbnails in the search return are displaying & that is all. Curators need to be able to scroll through the thumbnails for all available results to select the best thumbnail.
<img width="1247" alt="screen shot 2016-08-28 at 3 22 06 pm" src="https://cloud.githubusercontent.com/assets/3210225/18037253/682b912e-6d34-11e6-896c-1621b551fb16.png">

**Comment by jkeck** [comment]
We currently limit the number of results retuned to 10 (both via the solr query as well as the typeahead configuration).

I propose that we:

1. Increase that limit to 100 items.
2. Add a `max-height` and `overflow` properties to the dropdown so that it displays 5 items and can be scrolled.

@ggeisler does that sound reasonable to you?

**Comment by ggeisler** [comment]
Yes, that sounds excellent to me. Thanks.

**Comment by cbeer** [comment]
I'm unable to recreate this. I am able to scroll through the list, and it isn't truncated by the bottom of a page.

![screen shot 2017-02-07 at 5 07 35 pm](https://cloud.githubusercontent.com/assets/111218/22718945/fdd8cc7a-ed57-11e6-81da-63fef4c5f9b0.png)
