### ISSUE TITLE
Bug in Feature Page widget?

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1615]
Although #1613 seems to have fixed the issue with the browse category and feature page widgets, a curator just reported a problem with the feature page widget that I've confirmed.

I don't know that this is directly related to the work on #1613 at all (probably isn't) but does involve the same widget, so @jkeck if you have any ideas while that code is fresh in your mind...

In a particular exhibit, while the browse category widget works, the feature page widget won't show any results when entering a title in the input box, even though there are a couple of dozen existing feature pages. Here's a (Stanford superadmin access only) test page where you can see the problem by editing the page and trying to use the feature page widget at the bottom. An example feature page that should show up starts with "Janine".

https://exhibits.stanford.edu/women-art-revolution/feature/testing-feature-page-widget

I've confirmed that the updated feature page widget code works in several other exhibits on -prod, so why it doesn't work in just this exhibit is puzzling (I hope I'm not missing something obvious...).

**Comment by jkeck** [comment]
@ggeisler I think only published feature pages show up in the auto-complete.  Is that possibly a reason?

**Comment by jkeck** [comment]
Yeah, it looks like we use the `published` scope for the pages autocomplete: https://github.com/projectblacklight/spotlight/blob/master/app/controllers/spotlight/pages_controller.rb#L21

**Comment by ggeisler** [comment]
Yeah, I figured that. But in my testing I published a couple of pages and it still didn't work. 

I've just published two pages that start with "J" and it looks like it still isn't working?

**Comment by jkeck** [comment]
Just making the results of the discussion w/ @ggeisler public.

I believe that the twitter typeahead library is caching the results (even though we set the `ttl` to `0`).

So the user goes to the page w/ no published pages and that result is cached.  If they publish pages, the twitter typeahead library is fetching the cached result.

Not sure if this is an issue w/ the twitter typeahead library or what.

A workaround for the time-being is to open a browser in a new session (after publishing the pages) so that they don't have a cache of the results.

To address this ticket we should figure out how to **actually** disable the caching.

**Comment by ggeisler** [comment]
👍   The curator successfully used the workaround, but as you say, figuring out to disable the caching would prevent potential curator confusion in the future.
