### ISSUE TITLE
For uploaded images (not in the repository) -- ability to save a masthead does not work

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1752]
Curator Amy Hodge reports, "When I try to upload a masthead image, the software boots me back to exhibits.stanford.edu. I'll try to upload the screenflow video I captured. I tried this with two different mastheads I need to update on my exhibit and it happened on both." Please see MastheadError.mp4 file attached to: https://jirasul.stanford.edu/jira/browse/EXHBTF-152

**Comment by caaster** [comment]
Working with Amy on this, hold on...

**Comment by jkeck** [comment]
This is because we're not checking the correct user permissions when uploading these images (which explains why it's only affecting upload).

We typically determine if a user can do something by checking to see if they have access to the associated exhibit.  However, `FeaturedImages` don't have an associated exhibit, and the relationship goes the other way (e.g. a browse category stores the ID of its masthead and thumbnail, not the other way around).

One approach that we use for paper-trail versioning is just to to check if the user has any role.  This could potentially work for FeaturedImages as well since the initial create (via ajax upload) is the only permission we're talking about here (and any updating is already happening correctly through the associated object).

We're going to test this fix out in sul-dlss/exhibits#440.
