### ISSUE TITLE
Bug when trying to edit feature page

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1774]
Curator reported, and validated bug. Try to edit the following feature page and message says page doesn't exist. This feature page is viewable, however. https://exhibits.stanford.edu/stanford-pubs/feature/student-publications
<img width="624" alt="screen shot 2017-03-17 at 4 43 37 pm" src="https://cloud.githubusercontent.com/assets/3210225/24066547/ef0333d8-0b30-11e7-8ee8-9a166ad3ce81.png">

**Comment by caaster** [comment]
I can't replicate this bug on other feature pages, in this exhibit or in other exhibit feature pages. However, for many feature pages in this exhibit and in other exhibits, when I try and edit a feature page I see this: 
![screen shot 2017-03-20 at 8 42 59 am](https://cloud.githubusercontent.com/assets/3210225/24107965/7893aeec-0d49-11e7-8a16-2c84cc011f76.png)

**Comment by caaster** [comment]
For a bit more context, this bug has been occurring in Spotlight since Feb. 10, 2017. https://app.honeybadger.io/projects/49092/faults/32646884#notice-summary

The Honeybadger info makes it look like a bad image request on page load.

**Comment by caaster** [comment]
Just on the off chance this is related.....

blalbritton [9:21 AM] 
Cathy - the bug we’re running into with Spotlight is this one: https://app.honeybadger.io/projects/49092/faults/32646884

[9:21]  
it has been occurring since Feb. 10

[9:22]  
You can see that it relates to the Riiif request - probably for a banner image? Maybe something else. Even stranger is that it is a request for a 1px x 1px image and trying to stretch it to 400,400.

**Comment by jkeck** [comment]
The honey badger issue is unrelated.  The reason we don't see this in honeybadger is because there is an `ActiveRecord::NotFound` error occurring (which are intentionally not reported to honeybadger).

The reason this is happening is because the one of the browse categories that is in the browse category block on that page was either removed or had its slug/id changed.  We handle this on the rendering side of things, but something w/ how the resulting JSON is deserialized that is getting an `ActiveRecord::NotFound` and throwing an error page.

The widget should handle this better, but we can also fix the data in the db to fix it immediately.

**Comment by jkeck** [comment]
Added an issue to fix the underlying problem: #1782

The data in our site has been fixed manually.
