### ISSUE TITLE
thumbnails not working for about pages

### ISSUE THREAD

**Issue by starsplatter** [projectblacklight/spotlight#1806]
Locally we were having difficulty getting thumbnails to work on about pages. It appears to me that

accepts_nested_attributes_for :thumbnail, update_only: true, reject_if: proc { |attr| attr['iiif_tilesource'].blank? }

which appears on the features_pages model needs to get added to the about_pages model (or maybe it should really be up on the pages model)?  

if this seems like the right thing to do, let me know and I can attempt a pull request.

**Comment by jkeck** [comment]
@starsplatter I think I remember us discussing something similar (expanding the thumbnail ability to all pages).

I think you're on the right track.  👍 to submitting a PR to address this.

**Comment by ggeisler** [comment]
We need this feature working for Stanford exhibits so when a developer can look into it here's some updated info:

@starsplatter's PR above in the https://github.com/cul-it/exhibits-library-cornell-edu repo appears to add this line to `models/spotlight/about.rb`:

```
accepts_nested_attributes_for :thumbnail, update_only: true, reject_if: proc { |attr| attr['iiif_tilesource'].blank? }
```

When I add that line to spotlight running locally, it does indeed enable me to select and save an About page thumbnail, when I use an exhibit item image as the source. So that's great.

But it seems to prevent me from using an uploaded image as the thumbnail source.
