### ISSUE TITLE
Make default display for slideshow view be title only

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1810]

**Comment by ggeisler** [comment]
Just noting that we currently don't show any metadata (other than title when viewing an item in the slideshow) for slideshow view no matter what the user has enabled on the Metadata configuration page. So practically speaking, we already do what this ticket is asking for.

That said, unchecking all the Configuration > Metadata fields for Slideshow by default would be an improvement in that the UI would more closely match what happens in the actual slideshow view. Even better, perhaps we should actually disable all the checkboxes for Slideshow view, unless we want to update things so that in the Slideshow itself we do show the fields that are enabled in Configuration > Metadata for Slideshow view.

**Comment by drh-stanford** [comment]
I have a branch going for this: https://github.com/projectblacklight/spotlight/compare/deselect-as-default
