### ISSUE TITLE
User should stay on Config > Languages tab when adding language or saving

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1932]
Currently, when the user adds a language on the Configuration > Languages tab (https://github.com/projectblacklight/spotlight/pull/1927) they end up back on the Configuration > General tab. Same thing happens when the user makes a change to the Current Languages table and saves the page.

The user should stay on the Configuration > Languages tab when adding a language or selecting Save on the page. This would be consistent with the Save behavior on the other tabs within Configuration, and more helpful for the user who wants to add multiple languages or make a language public after adding it.

**Comment by camillevilla** [comment]
@ggeisler After clicking through some other Configuration tabs, I don't think this is behavior we currently have implemented in Spotlight. Other Configuration options will redirect to the first tab in the group after saving changes.

![tab-clicks](https://user-images.githubusercontent.com/5402927/37374648-566bf68a-26d9-11e8-9657-80f68ab77d62.gif)

There are two things we would need to do to implement this.
1. clicking on the button redirects to a link with an anchor tag for the appropriate tab at the end (e.g. `http://localhost:3000/spotlight/test/edit#language`). 
2. writing some Javascript so that the right tab shows up when you navigate to edit#language

We have behavior (1) for the Configuration > Languages tab, but not (2). 

![add-language](https://user-images.githubusercontent.com/5402927/37375179-ba0a7ff2-26db-11e8-9fa7-7e3d34c400de.gif)

We do not have behavior (1) implemented on the other Configuration tabs. I definitely agree that this would be a great improvement to the user experience. However, implementing a consistent experience across the Configuration panel would be more of an undertaking. Could we re-title this ticket to reflect that broader scope?

**Comment by ggeisler** [comment]
Oops, you're right @camillevilla. Sorry about that, I swear I double-checked when writing the ticket but now that I check again, I see that it doesn't work the way I though it did. Not sure how I checked it earlier and got what I thought was a different result.

The case I think is most important is when the user adds a language, because a) it helps them understand/confirm what they've done if they see the language actually show up in the Current Languages table and b) if they want to add multiple languages at once they don't have to return to the tab.

I'm less concerned about the Save behavior. It would be nice but as you point out, @camillevilla, if we did it here we should probably do it for all Admin tabs, which is a much larger undertaking.

@mejackreed @camillevilla Could we just stay on the same page when adding a language and maybe not worry about the Save behavior for now?

**Comment by jkeck** [comment]
I think the solution where we pull the parameter is a better solution.  Having to make the "Add Language" be able to submit asynchronously could potentially add quite a bit of complexity (which there is already an established pattern for making a particular tab active).

**Comment by ggeisler** [comment]
(To be clear, I wasn't asking for a particular implementation approach. Just don't want the user to have to navigate back to the page to confirm that the language they added was actually added to the Current Languages table, however that can best be done.)

**Comment by jkeck** [comment]
Totally, we chatted a bit about doing the async approach when we were paring on this, so that def. came up as something that would be nice to have, but there were definitely concerns raised about the complexity.  I think ultimately most, if not all, of the tabs could benefit from this sort of thing, so it might be nice to build it in while we are here (assuming it doesn't become more difficult).

**Comment by jkeck** [comment]
I would be 👍 to expanding the scope of this issue to at least address the tabs in the General Settings tabs.

**Comment by camillevilla** [comment]
- Addressed in #1942 
- Merged into spotlight#i18n-🌝for Spotlight 2.0
