### ISSUE TITLE
Add progress indicators to translation editing screen

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#1935]
Split out of #1914

**Comment by camillevilla** [comment]
@ggeisler we're working on this right now and the contrast between the tab label (#777777) and the progress count (#686868) is pretty low. I think the original mockups used the font colors from Exhibits.

<img width="576" alt="progress_bars" src="https://user-images.githubusercontent.com/5402927/37856509-fd468332-2eb1-11e8-907d-6ed99b0ffa5c.png">

@jkeck suggests using these [badge components from Bootstrap 3](https://getbootstrap.com/docs/3.3/components/#badges) because they automatically adjust to contrast with the tab background.

<img width="542" alt="badges" src="https://user-images.githubusercontent.com/5402927/37856632-c7775032-2eb2-11e8-8063-541c0e4d1379.png">

**Comment by ggeisler** [comment]
Yep, sorry about that. The suggestion to use the BS badges is great, I like it.

**Comment by camillevilla** [comment]
@ggeisler I have one more design question. Should the progress counter numbers reflect:
(a) the number of total available fields for translation, or 
(b) the number of fields that have been filled out in the default language? 

Here's a small example where the curator has not provided a sub-title. We currently implement (a).

<img width="815" alt="two fields available for translation" src="https://user-images.githubusercontent.com/5402927/37858465-136cda2a-2ec2-11e8-9d28-33efad9deb88.png">

**Comment by ggeisler** [comment]
(a) is what I intended. Translated fields/total number of fields on the page

**Comment by camillevilla** [comment]
- Closed by #1961
- Merged into [i18n-🌝](https://github.com/projectblacklight/spotlight/tree/i18n-%F0%9F%8C%9D) feature branch for Spotlight v2.0.0
