### ISSUE TITLE
Look into responsiveness of translation forms

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#1957]
Since we're doing a bit of a custom form here, we should look at the responsiveness of the form before we repeat the pattern too much.

# Medium
<img width="728" alt="form-md" src="https://user-images.githubusercontent.com/96776/37798391-ceaa5928-2dd9-11e8-93fd-45db550d9510.png">

# Small
<img width="786" alt="form-sm" src="https://user-images.githubusercontent.com/96776/37798392-ced3bf2a-2dd9-11e8-9527-66837d949921.png">

# Extra Small
<img width="632" alt="form-xs" src="https://user-images.githubusercontent.com/96776/37798475-142f1290-2dda-11e8-9b13-90cc16d6f28a.png">

**Comment by ggeisler** [comment]
I think we can fix this pretty easily. Screenshots below are after I updated the `col-*` classes on the first two relevant columns like this:

```
-            <%= translation_fields.label :value, t("spotlight.search.fields.search.#{key}", locale: I18n.default_locale), class: 'control-label col-sm-2' %>
-            <div class='col-md-8 panel panel-body panel-translation'>
+            <%= translation_fields.label :value, t("spotlight.search.fields.search.#{key}", locale: I18n.default_locale), class: 'control-label col-xs-12 col-sm-2' %>
+            <div class='col-xs-11 col-sm-9 panel panel-body panel-translation'>
```

And the third column like this:

```
-            <div class='col-md-2'>
+            <div class='col-xs-1'>
```

I reduced the check icon column width to `col-xs-1` just because even at the smallest column size that is plenty wide for it, and although the inputs likely don't need to be as wide as they are on this tab, maybe on some of the other tabs the extra width for the inputs could be useful. 

## Extra Small
<img width="405" alt="xs" src="https://user-images.githubusercontent.com/101482/37805591-7076167a-2df8-11e8-90d5-5b551f9845b4.png">

## Small
<img width="600" alt="sm" src="https://user-images.githubusercontent.com/101482/37805597-779e4c24-2df8-11e8-919d-ec3b80dc47ba.png">

## Medium
<img width="840" alt="md" src="https://user-images.githubusercontent.com/101482/37805604-7daae686-2df8-11e8-8606-eee2a54bcb95.png">

## Large (XL is similar)
<img width="768" alt="lg" src="https://user-images.githubusercontent.com/101482/37805616-87c9054e-2df8-11e8-8fb3-31ea8c6055f2.png">

**Comment by jkeck** [comment]
That looks good to me @ggeisler.  👍 

Should we add this to Ready to be worked on?

**Comment by ggeisler** [comment]
I don't see why not. Whoever actually does the work can double-check things to make sure I didn't miss some reason why this might not be a good solution.
