### ISSUE TITLE
Locale-based main menu shows About when no About pages are published

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2047]
If I, as a curator, add a language and make it public, the exhibit visitor viewing the site in that locale will see the About menu item, even if no locale-specific about pages have been published. If no locale-specific About pages have been published, the About menu item for that locale should not be displayed (otherwise the visitor gets a Rails exception when clicking the About menu item).

Note that this does work correctly for feature pages. If I, as an exhibit visitor, view the site in a locale for which no feature pages have been published, I do not see the feature page menu item, which is the expected behavior.

#### Exhibit visitor viewing site in Spanish

<img width="506" alt="visitor" src="https://user-images.githubusercontent.com/101482/39496122-0a0aad78-4d52-11e8-8bb9-13c6f3912d8f.png">

---

#### Exhibit curator's view of About page status

<img width="440" alt="curator" src="https://user-images.githubusercontent.com/101482/39496149-177f3b9a-4d52-11e8-863d-a1f1abf116d8.png">

**Comment by jkeck** [comment]
@ggeisler what should the behavior be in the following case:

The Exhibit has a published English about page and an unpublished Spanish about page.  As an anonymous user I am on the English page and switch to Spanish.

**Comment by ggeisler** [comment]
@jkeck I think we put them on the homepage in Spanish. We know there is always a homepage, in every locale, so that seems like the reasonable fallback when a locale-specific equivalent doesn't exist or isn't published?

**Comment by jkeck** [comment]
@ggeisler I think there are some concerns around adding this redirect behavior.  It seems like we may be trying to code around issues that we don't intend/want people to get into the state of (e.g. Publishing languages that have incomplete translation status).  It seems like we want people to translate their entire site and then publish the language (and not leave certain pages unpublished).  This _could_ have SEO implications (having a translated page that now redirects to a page with different content).

Also, getting redirected to the home page may be disorienting for the exhibit curators/admins w/o proper explanation of what's happening.  As it is now, they'll get an error indicating that the page that they're looking for does not exist (which is more "true" to the current state) and could be more obvious that the issue is that they need to create/publish that translated page.

Possible other solutions would be to try and be more intelligent about how we build the locale switcher (which could potentially get complicated) or try to find a more specific error we could throw/catch to provide a better error message.

**Comment by jkeck** [comment]
Sorry for the confusion.  I wasn't advocating that we change how we allow users to make languages public, more that it seems like things have been designed to push the curator towards making all their translations before publishing languages (through good tools to quickly determine translation completion status and creating sane default behavior) and it feels like what we're trying to implement is something that is potentially facilitating publishing languages with incomplete translation status.

I guess what I'm advocating for is that we treat these translated pages like we do any other page and not have some special logic for it.  That behavior is:
- If I try to access an unpublished page that I shouldn't otherwise have access to, I get sent to the home page of the entire app w/ an "You are not authorized to access this page" flash message.
- If I try to access a page that doesn't exist at all, I get `The page you were looking for doesn't exist.` error page. (404 Not Found)

If we wanted a custom error page we would probably want to find a specific http status code to return and have a special error page template for it (which I'm not certain we'll have a semantically correct code better than 404).

One possibility (unless you feel strongly that this should be default behavior in Spotlight) would be to keep the existing behavior in Spotlight (Redirect w/ flash for Unauthorized access / 404 error for Not Found) and try to inject this customization locally.  This keeps Spotlight behaving the way it always has, and we could document our approach for those who are interested.  If it turns out to be something that would be broadly requested, we can look into putting this customization up-stream.

**Comment by ggeisler** [comment]
(@jkeck I was writing this at the same time as you were writing the above. Below is my suggestion for the redirect part of the issue. I'll react to the rest of your comment after reading through again.)

A further refinement of the idea of redirecting the user to the home page in the scenario where the user changes locale while on a page that isn't published in the new locale: if we add a flash message that explains to the user why they are now on the homepage, with an option to view the page they were previously on in English, that would seem to eliminate the potentially confusing aspect of this scenario, while minimizing the inconvenience because they are just one click from viewing the desired page in English. Something like:

<img width="511" alt="page-not-found-flash-message" src="https://user-images.githubusercontent.com/101482/39533627-69d53b64-4de4-11e8-93fa-6a224aef9b7f.png">

**Comment by ggeisler** [comment]
> - If I try to access an unpublished page that I shouldn't otherwise have access to, I get sent to the home page of the entire app w/ an "You are not authorized to access this page" flash message.
> - If I try to access a page that doesn't exist at all, I get The page you were looking for doesn't exist. error page. (404 Not Found)

So just to make sure I'm following, these two scenarios are equivalent to:
- Translated page created but not published
- Translated page not yet created

If so, I wonder if we couldn't just use the same redirect to home with flash message as in my screenshot above for both scenarios? Because from the user point of view they are the same scenario (I was viewing a page and switched locales, but the page I am on is not accessible to me in this new locale). In other words, the difference between an _uncreated_ and an _unpublished_ translated page is meaningless to the exhibit visitor.

Let me know if I'm still not getting it. In any case, I'm not opposed to keeping things as they are in Spotlight, and letting implementors (like us) refine the approach locally.

**Comment by jkeck** [comment]
> So just to make sure I'm following, these two scenarios are equivalent to:
> 
> * Translated page created but not published
> * Translated page not yet created

Yes, that is correct.

One clarification I should make is that attempting to access a page you don't have access to actually redirects you to the root of the entire site (not the particular exhibit).  _(This is how it has been all along)_

I'm thinking we should break this out into a separate issue.  We can write up some code that would do this (and decide if that should be local or in Spotlight) and we can use that as a springboard for conversation around that particular behavior/feature.

**Comment by ggeisler** [comment]
> One clarification I should make is that attempting to access a page you don't have access to actually redirects you to the root of the entire site (not the particular exhibit). (This is how it has been all along)

Yeah, that is important to consider. I mean, the current approach is okay if we don't think about the multilingual scenario because the page-you-don't-have-access-to situation probably rarely occurs (which is why it hasn't really come up as a problem before, I'm guessing). But in a multilingual exhibit, with the approach we're taking to making creating and publishing locale versions of pages optional, the page-you-don't-have-access-to situation could come up a lot more often (relatively, anyway; I'd think the odds of a user changing the locale when on an locale-unpublished page seems pretty low in general), and putting the user on the site root page would be very confusing.

So, yes, your suggestion for creating a separate issue and talking this through further sounds great.

**Comment by jkeck** [comment]
Remaining work outlined in #2052
