### ISSUE TITLE
Item carousel widget needs better next/prev icons

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#2336]
Split out while working on #2333 

<img width="874" alt="Screen Shot 2019-12-10 at 7 14 30 AM" src="https://user-images.githubusercontent.com/96776/70542017-e4ce9700-1b1c-11ea-9e45-fa9d83a2b130.png">

**Comment by ggeisler** [comment]
Do you think these will work?

- https://material.io/resources/icons/?icon=arrow_back_ios&style=sharp
- https://material.io/resources/icons/?icon=arrow_forward_ios&style=sharp

**Comment by jkeck** [comment]
@ggeisler I suppose I'm a bit concerned about how those will look on a black background/dark image.  I guess there may not be an icon that does much for us in this respect and we may be better off adding a drop-shadow w/ a background that has the opacity turned down w/ the material icons listed above.

**Comment by ggeisler** [comment]
@jkeck Yeah, I know what you mean but I don't think it is an icon issue as much as a styling issue, as you suggested. In Exhibits currently the icon looks a little fatter, which is good, but I'm not sure if that is just due to the larger, scaled up size:

<img width="825" alt="Screen Shot 2019-12-10 at 4 45 54 PM" src="https://user-images.githubusercontent.com/101482/70579083-d0b28600-1b6c-11ea-8b76-0cd000450d60.png">

I'm hoping the MUI icons I listed above will feel fat enough when scaled up some, and then we can deal with the drop shadow aspect separately to make sure they are always visible. As a starting point, if it isn't already in the Spotlight code, might be what we do in Exhibits above (there is mouseover-triggered background darkening)?

I don't think we've ever had ideal slideshow/carousel styling; it's hard when you don't know what the background  color of your images are going to be. But maybe we can work on that during the next Exhibits workcycle.

**Comment by jkeck** [comment]
@ggeisler definitely agree.  And I didn't mean to indicate that I didn't think those icons should be used (just that we may want to do something in addition to that).  Perhaps in a future work cycle, as you mention.
