### ISSUE TITLE
Enable bulk tagging (add, edit, delete) of exhibit items

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2346]
Several institutions have indicated in the community roadmap that they are interested in offering their exhibit curators the capability to edit exhibit item tags in bulk. We have interest in this at Stanford as well.

**Comment by jacobthill** [comment]
One question I have for DLME is how bulk tags will work with changing data? If I tag a group of record with a 'bulk-tag' and then notice an error in the data transformation, delete the records, then re-transform them, will the 'bulk-tag' be lost? Can it be identifier aware so that as long as the id doesn't change, the tag will be reapplied?

**Comment by cbeer** [comment]
Fixed by bulk updates?
