### ISSUE TITLE
Enable customization of behavior for browse category results that do not display the facets

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#2595]
Spun out of conversation in https://github.com/sul-dlss/dlme/issues/1086

Looking at: https://github.com/projectblacklight/blacklight-gallery/search?q=row-cols-md-3

It seems like `row-cols-md-3` might be better suited to a `row-cols-md-4` when facets are not being displayed.

@ggeisler ?

Example browse category: https://dlmenetwork.org/library/browse/622-900-ce

**Comment by ggeisler** [comment]
@mejackreed  Sure. `row-cols-md-4` would show more images in the same amount of space, with the tradeoff of making the images smaller.

I checked how the change looks in a few different exhibits and in some cases the amount of detail you can see in the image is noticeably reduced (more obvious with photography exhibits than DLME) but not enough that I think it's a problem, given this is a results page and we're only trying to provide enough of a preview to help the user decide whether to check out the detail page. And the change does make pages with vertically-oriented items look better, since those tend to be too tall with the 3-col layout.

So I'd be fine with this change (assuming I'm correct in my assumption that this only affects gallery view of browse results pages; if it affects something else I'm not catching let me know so I can take a look).
